[package]
name = "T766-ControlClient"
version = "0.1.0"
edition = "2024"

[dependencies]
minreq = { version = "2.14.1", features = ["https-rustls"] }
tempfile = "3.24.0"
tar = "0.4.44"
gethostname = "1.1.0"
